/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CG DEADPOOL (https://sketchfab.com/Osman23)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spiderman-far-from-suit-5f6157f8b0b1405fa63aca154b2debd1
Title: Spiderman Far From Suit
*/
import spider from "../assets/spiderman_far_from_suit.glb";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useSnapshot } from "valtio";
import state from "../store";

const Model = (props) => {
  const { nodes, materials } = useGLTF(spider);
  const states = useSnapshot(state);
  const ref = useRef();

  return (
    <group {...props} dispose={null} scale={0.09}>
      <group
        name="RootNode"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        userData={{ name: "RootNode" }}
      >
        <group name="Object_7" userData={{ name: "Object_7" }}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            name="Object_246"
            geometry={nodes.Object_246.geometry}
            material={materials.Cristal_Eyes}
            skeleton={nodes.Object_246.skeleton}
            userData={{ name: "Object_246" }}
          />
          <skinnedMesh
            name="Object_254"
            geometry={nodes.Object_254.geometry}
            material={materials.Eyes_Black}
            skeleton={nodes.Object_254.skeleton}
            userData={{ name: "Object_254" }}
          />
          <skinnedMesh
            name="Object_256"
            geometry={nodes.Object_256.geometry}
            material={materials.Tom_Mask}
            skeleton={nodes.Object_256.skeleton}
            userData={{ name: "Object_256" }}
          />
          <skinnedMesh
            name="Object_260"
            geometry={nodes.Object_260.geometry}
            material={materials.Tom_Arms}
            skeleton={nodes.Object_260.skeleton}
            userData={{ name: "Object_260" }}
          >
            <meshStandardMaterial attach="material" color={states.color} />
          </skinnedMesh>
          <skinnedMesh
            name="Object_262"
            geometry={nodes.Object_262.geometry}
            material={materials.Tom_Torso}
            skeleton={nodes.Object_262.skeleton}
            userData={{ name: "Object_262" }}
          />
          <skinnedMesh
            name="Object_264"
            geometry={nodes.Object_264.geometry}
            material={materials.Tom_Suit}
            skeleton={nodes.Object_264.skeleton}
            userData={{ name: "Object_264" }}
          />
          <skinnedMesh
            name="Object_266"
            geometry={nodes.Object_266.geometry}
            material={materials.Tom_Boots}
            skeleton={nodes.Object_266.skeleton}
            userData={{ name: "Object_266" }}
          />
          <skinnedMesh
            name="Object_268"
            geometry={nodes.Object_268.geometry}
            material={materials.Tom_legs}
            skeleton={nodes.Object_268.skeleton}
            userData={{ name: "Object_268" }}
          >
            <meshStandardMaterial attach="material" color={states.color} />
          </skinnedMesh>
        </group>
      </group>
    </group>
  );
};

export default Model;
